### ISSUE TITLE
Naan bread recipe doesn't specify salt amount

### ISSUE THREAD

**Issue by phenylcyclidine** [ronaldl29/public-domain-recipes#4]
See https://publicdomainrecipes.com/naan-bread/
I made this and used between 1&1/4 - 1&1/2 teaspoons looking at other recipes and accounting for the amount of flower, it turned out good but I'm just guessing. 
Recipe by @niharokz

**Comment by ronaldl29** [comment]
Thank you for pointing this out @phenylcyclidine Fixed with https://github.com/ronaldl29/public-domain-recipes/pull/5
