### ISSUE TITLE
Add Logianer's Basic Waffles Recipes from his fork.

### ISSUE THREAD

**Issue by kingofcube** [ronaldl29/public-domain-recipes#6]
https://github.com/Logianer/based.cooking

"Added recipe for basic waffles

Upload 2 images for the recipe
Added author information in data/authors/
Added tag (+styles): 'waffle'"

**Comment by ronaldl29** [comment]
Thanks for the heads up!
Added here: https://publicdomainrecipes.com/basic-waffles/
And in this PR: https://github.com/ronaldl29/public-domain-recipes/pull/8
@kingofcube

**Comment by ronaldl29** [comment]
I didn't even think to tag you when this was made. 😂 Anyways, welcome to the repo! @Logianer
