### ISSUE TITLE
Is putting other people's recipes from youtube for example allowed?

### ISSUE THREAD

**Issue by kingofcube** [ronaldl29/public-domain-recipes#7]
wanted to out on of adam ragussas recipes.

**Comment by kingofcube** [comment]
@ronaldl29 ?

**Comment by ronaldl29** [comment]
Hi @kingofcube Content published online is generally copyrighted by default. I would suggest contacting him and get written permission to release his recipes as public domain. This article here: https://www.copyrightlaws.com/copyright-protection-recipes/
Spells out the specifics of copyright and recipes in particular.

**Comment by kingofcube** [comment]
Oh mkay, thanks! Might aswell close this lol
