### ISSUE TITLE
Add these people's forks

### ISSUE THREAD

**Issue by kingofcube** [ronaldl29/public-domain-recipes#9]
Haven't seen them in the website, also i haven't checked the actual content themselves so um yea you might do a bit of quality control.
https://github.com/LukeSmithxyz/based.cooking/pull/974
https://github.com/LukeSmithxyz/based.cooking/pull/946

Also found this, it was declined because the owner didn't even add 3 lines of text, lol, anyway you can just put the fork on the website and add the 3 lines.
https://github.com/LukeSmithxyz/based.cooking/pull/372

Maybe you should find more forks from based.cooking and add them onto this repo, idk im not your boss so you can do whatever you want.

**Comment by ronaldl29** [comment]
I will get these added tomorrow. Thank you! @kingofcube

**Comment by kingofcube** [comment]
No problem!

**Comment by ronaldl29** [comment]
Added butter cake recipe https://github.com/ronaldl29/public-domain-recipes/pull/11

**Comment by ronaldl29** [comment]
Blueberry muffins added already

**Comment by ronaldl29** [comment]
Added recipes
